### ISSUE TITLE
BigQuery accepts 100,000 rows per second

### ISSUE THREAD

**Issue by fhoffa** [lnklnklnk/ga-bq#16]
Note that the project docs say: " you can not insert more than 1000 rows into bigquery at once" - but in reality BigQuery will accept upto 100,000 rows per second via streaming.

https://cloud.google.com/bigquery/quota-policy#streaminginserts

![image](https://user-images.githubusercontent.com/4095866/28442320-a375bb34-6d64-11e7-89a7-0780708d5e9c.png)

**Comment by lnklnklnk** [comment]
You're right.
But there is a limit in lease_task method: https://yadi.sk/i/2BmdUAQ63LG4Rp

Fixed it in README.

Thanks you!
